### PR TITLE
build: Notarize the build with Apple

### PR DESCRIPTION
**Pull request by felixrieseberg**
Now that people are finally picking up Catalina, we should really notarize Fiddle. This PR ensures that we do.

### CODE REVIEW

**Comment by malept** [comment]
@felixrieseberg is there a reason why you didn't use [`osxNotarize`](https://github.com/electron/electron-packager/blob/v14.1.1/docs/api.md#osxnotarize) in `packagerConfig`?

**Comment by felixrieseberg** [comment]
@malept We could, but we should bump the `electron-packager` dependency in `electron-forge` to actually pick up the recent version!

```
🐦  ➜  fiddle  npm ls electron-notarize
electron-fiddle@0.11.1 /Users/felixr/Code/fiddle
├─┬ @electron-forge/cli@6.0.0-beta.45
│ └─┬ @electron-forge/core@6.0.0-beta.45
│   └─┬ electron-packager@14.0.6
│     └── electron-notarize@0.1.1 
├─┬ @electron-forge/maker-deb@6.0.0-beta.45
│ └─┬ @electron-forge/shared-types@6.0.0-beta.45
│   └─┬ @types/electron-packager@14.0.0
│     └── electron-notarize@0.1.1 
└── electron-notarize@0.2.1 
```

**Comment by malept** [comment]
That'd do it. I'm in the middle of fixing a bug in Electron Forge, so once I finish that, I'll release a new beta.

**Comment by malept** [comment]
Forge 6.0.0-beta.46 was released last night!

**Pull request merged**
