### PR TITLE
feat: enable options for the text editor

### PR DESCRIPTION
**Pull request by nctl144**
Hey @felixrieseberg , I made this PR to follow up with what we were talking about in #88. I am interested in adding more options to Fiddle (other than just soft wrap option). Although I am a little bit confused right now, but I believe adding soft wrap first will be a good start.

### CODE REVIEW

**Comment by nctl144** [comment]
I kinda figured out how to get the value from the JSON file and fire the event when the "toggle soft wrap" option is clicked. But I have no idea how to restart the editor and write on the json file when users select "toggle soft wrap".. 😄

**Comment by nctl144** [comment]
I finally got it working @felixrieseberg! The "toggle soft wrap" button is now functioning :) Can you please help me review this PR when you have time? I will start working on other options after this is reviewed 😄

**Comment by nctl144** [comment]
I just added 'minimap' toggle as an extra option. The code can definitely be optimized later 😄

**Comment by felixrieseberg** [comment]
This is great stuff, thank you so much!

**Comment by nctl144** [comment]
Thank you @felixrieseberg for your feedback 😄

**Pull request merged**
