### PR TITLE
fix: race condition when getting Node types

### PR DESCRIPTION
**Pull request by dsanders11**
Found the race condition that's been haunting the tests.

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]

**Review by georgexu99 — APPROVED** [review]
adding extra lib -> 52 times seems a bit weird to me but if that can be explained then its a gogogo from me

**Comment by dsanders11** [comment]
> adding extra lib -> 52 times seems a bit weird to me but if that can be explained then its a gogogo from me

@georgexu99, there are 51 individual `*.d.ts` files are in the Node typings ([see the test fixture](https://github.com/electron/fiddle/blob/37f259a59f26410b1e2e4ca1b9b67386cf577b4a/tests/fixtures/node-types.json)). Then there's one `electron.d.ts` file, for 52 total.

**Comment by malept** [comment]
> > adding extra lib -> 52 times seems a bit weird to me but if that can be explained then its a gogogo from me
> 
> @georgexu99, there are 51 individual `*.d.ts` in the Node typings ([see the test fixture](https://github.com/electron/fiddle/blob/37f259a59f26410b1e2e4ca1b9b67386cf577b4a/tests/fixtures/node-types.json)). Then there's one `electron.d.ts` file, for 52 total.

IMO that should be a comment right next to that 52 magic number in the test. Having a future developer dig through PRs to find an explanation is suboptimal.

**Comment by dsanders11** [comment]
Good point @malept. I'll make a note to do a follow-up PR that adds that context and some more context to some of the other tests in the same area as well.

**Pull request merged**
