### PR TITLE
feat: Add bisect complete dialog

### LINKED ISSUE #299: Add bisect complete dialog
I've noticed that the bisect result is pretty easy to lose in the console scrollback. In addition to logging the result, I'd love a dialog to display it and let me know the bisect is complete.

### PR DESCRIPTION
**Pull request by issacgerges**
Closes #299.

This change adds a dialog to show when the bisect is complete (to prevent the user from losing the complete log in their console scrollback).

bisect-complete

### CODE REVIEW

**Comment by issacgerges** [comment]
I noticed a few times at Covalence and training that the console message required people to squint to find. No worries if this is something that was discussed before and decided against!

**Comment by erickzhao** [comment]
> No worries if this is something that was discussed before and decided against!

Not at all, I think this is a great proposal. Will give this a look soon. :)

**Comment by issacgerges** [comment]
Makes sense, will do

**Comment by issacgerges** [comment]
@erickzhao it's a bit more disruptive now, but I've refactored `<WarningDialog>` and `<ConfirmDialog>` into a general `<GenericDialog>` that supports types `warning`, `confirm`, and `success`.

**Pull request closed without merging**
