### PR TITLE
fix: theme select popover closing settings when pressing escape

### PR DESCRIPTION
**Pull request by mwoodhousemckenzie**
Closes https://github.com/electron/fiddle/issues/322

I added a state listener for when someone opens the theme selector. I could not figure out a way to stop the events from propagating and closing the settings besides this solution. It might be better to make this more generic of `prevenSettingsClose` or something, but I am not sure.

ezgif com-optimize

I saw that this is a good first issue to test my OSS contributions on, I am mainly an Angular developer and have only dabbled a little in React so if there is a better way to make these changes, please let me know.

### CODE REVIEW

**Review by erickzhao — CHANGES_REQUESTED** [review]
Hey @mwoodhousemckenzie, thanks for the contribution! I think you're on the right track here,  and here's a proposal to generalize that involves moving some functionality around:

* In `src/renderer/components/settings.tsx`, set a local state variable in the component that's something like `hasPopoverOpen` (similar to the `appState.isThemeSelectorShowing` variable).

* Create a helper function `toggleHasPopoverOpen` in `src/renderer/components/settings.tsx` (similar to the `toggleThemeSelectorOpened()` function, but modifies the local state variable instead).

* Pass `toggleHasPopoverOpen` down as a prop to `src/renderer/components/settings-general-appearance.tsx` and use it in the same way as your previous function.

This should generalize it so that if any other settings page has a Popover with the same kind of interaction, we should be able to program the same state variable accordingly.

**Comment by mwoodhousemckenzie** [comment]
@erickzhao Perfect. Thanks for the feedback! I was wondering if it should be more generic. I updated the code to be more generic now 😄

**Review by erickzhao — CHANGES_REQUESTED** [review]
Hey @mwoodhousemckenzie, this looks great!

One thing to change that's completely not your fault: the listener for the `Esc` key actually never unmounts because I didn't pass it the correct (`true`) argument when initially adding this feature. This makes it so that your fix doesn't actually work for subsequent instances of the Settings pane.

Could you change line 56 of `src/renderer/components/settings.tsx` to this?

```diff
  public componentWillUnmount() {
-   window.removeEventListener('keyup', this.closeSettingsPanel);
+   window.removeEventListener('keyup', this.closeSettingsPanel, true);
  }
```

**Comment by mwoodhousemckenzie** [comment]
Ah good catch @erickzhao, don't know why I didn't notice that. Thanks for pointing it out!

**Review by erickzhao — APPROVED** [review]

**Comment by mwoodhousemckenzie** [comment]
> @mwoodhousemckenzie could you follow the instructions at #449 and force push until you get the Travis build to pass? I can't merge the PR in until it passes.
> 
> Sorry about this, it's an upstream issue that happens a bit too often. 🙇

Travis build has passed but the coveralls and circlici builds are failing, is there anything I can do to get those to pass?

**Comment by erickzhao** [comment]
> Travis build has passed but the coveralls and circlici builds are failing, is there anything I can do to get those to pass?

You don't have to worry about those for the purposes of this PR:
* You could add unit tests for Coveralls to cover more lines of code, but this is very optional.
* Our CircleCI has been a WIP for a while now, and can safely be ignored.

I'll merge this in soon unless you feel like adding more tests!

**Comment by mwoodhousemckenzie** [comment]
Unless there is any tests you see I should add I am good with this. Thanks for helping me on my first PR in this repo, greatly appreciated 😄

**Pull request merged**
