### PR TITLE
fix #1361 callback-to-promise

### LINKED ISSUE #1361: Show Me Examples Still Use Callback APIs
There's a handful of outdated show me examples which need to be migrated to using the promise APIs, e.g.

https://github.com/electron/fiddle/blob/f8deba908f8b72942002d89ef7350ee21b4848a5/static/show-me/session/main.js#L19-L21

### PR DESCRIPTION
**Pull request by shankeleven**
fixes #1361 
replaced outdated callbacks with promise.then()

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]

**Review by dsanders11 — CHANGES_REQUESTED** [review]
Thanks for the PR, @shankeleven! The referenced code in that issue is just one example, to close that issue we need to address all cases. Do you plan to update this PR to fix all of them? Otherwise we'll need to tweak the description so that issue remains open.

[This old doc](https://github.com/electron/electron/blob/5-0-x/docs/api/promisification.md) should help with identifying APIs that were changed from callback to promises.

**Comment by shankeleven** [comment]
Sure, i'll try to find and correct as many as i can

**Comment by codebytere** [comment]
@shankeleven do you still plan to work on this?

**Comment by shankeleven** [comment]
Sorry, i guess i wouldn't be able to do it due to some medical reasons, i apologise for taking the job and not being able to deliver

**Comment by dsanders11** [comment]
No problem @shankeleven. Get well. ❤️

**Pull request closed without merging**
