### PR TITLE
test: use snapshots to properly test version-select component

### PR DESCRIPTION
**Pull request by aryanshridhar**
https://github.com/electron/fiddle/pull/1160#issuecomment-1259827500

### CODE REVIEW

**Comment by aryanshridhar** [comment]
cc @georgexu99 @dsanders11 :)

**Comment by georgexu99** [comment]
The test looks good, but I'm thinking that we should put this test with the rest of the PR? @dsanders11 

Also, perhaps this is a bit of an unfounded worry, but given the size of the other PR and its age, it may honestly be easier reapply the changes on top of main (with a careful cherry-pick or by hand), unless merging the new main changes don't pose a huge problem

**Review by erickzhao — CHANGES_REQUESTED** [review]
I would lean against replacing the existing assertion with a snapshot test.

IMO this change makes it harder to read what the exact assertion is and makes the test more brittle to any change in the component (easy to get false positives).

**Comment by dsanders11** [comment]
@erickzhao makes a good point about this making the test more brittle. Let's find a different way to fix the test failure in #1160. Sorry about the churn, @aryanshridhar.

**Comment by aryanshridhar** [comment]
No worries :)
Closing in favor of point put up by @erickzhao.

**Pull request closed without merging**
