### PR TITLE
fix: Inserted whitespace in tour

### LINKED ISSUE #235: Spacing issues with <code> tags in tour
image

this should be `calls BrowserWindow`

### PR DESCRIPTION
**Pull request by arnitkun**
The fiddle tour had missing spaces in the modal for main window and HTML window. Also, the snapshots are updated to make sure this passes the tests. Fixes #235.

### CODE REVIEW

**Comment by arnitkun** [comment]
Hmm..the build is failing. I have only placed a couple of whitespaces. The branch is not behind master.

Has there been any change or did I miss something? Sorry for the basic question.

**Comment by erickzhao** [comment]
@arnitkun Snapshots would need to be updated accordingly. :)

**Comment by arnitkun** [comment]
Oh..I did it the first time but didn't for the second one. Thank you for
pointing this out. 😃

**Comment by arnitkun** [comment]
Updated snapshots.

**Pull request merged**
