### PR TITLE
chore: add `quick-start` folder to `static`

### PR DESCRIPTION
**Pull request by erickzhao**
Ref: #411 

This PR adds a separate folder for each major branch of `electron-quick-start`. The eventual goal is to change the content of a new Fiddle based on the currently-selected major version.

For now, these files are added with no changes to existing code paths. The goal is to add a GitHub Actions cron that will periodically update this content from the `electron-quick-start` source using Octokit.

### CODE REVIEW

**Comment by malept** [comment]
I'm curious if you considered using git submodules instead.

**Comment by erickzhao** [comment]
@malept I haven't! Would this involve running a script to `git submodule add` each major version branch into a separate submodule? I haven't worked much with submodules in the past.

Also, wondering what the major benefit of submoduling here would be. Reduced dependency on Octokit?

**Comment by malept** [comment]
> I haven't! Would this involve running a script to `git submodule add` each major version branch into a separate submodule? I haven't worked much with submodules in the past.

Yes, I believe so.

> Also, wondering what the major benefit of submoduling here would be. Reduced dependency on Octokit?

Reduced dependency on Octokit, and we can leverage [Dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem) to update!

**Comment by ckerr** [comment]
Hey, I'm revisiting this because whatever option we use to populate quick-start templates could also be used to populate test templates for #591.

Strong agree with @malept's dependabot comment, I like the idea of not needing manual upkeep PRs. About submodules though I don't think I see the big picture yet: if someone downloads a Fiddle release instead of cloning the Fiddle repo, how would the "New Fiddle" button work? At that point is there even a submodule to use?

* If we want to make things static, we could probably write a script to automatically populate templates in `static/` from electron-quick-start (the result would look a lot like the diffs in this PR) and then have a PR new updates whenever electron-quick-start gets new commits. Advantages: no new magic needed at runtime. Disadvantage: more scripts & bots to break, and old versions of Fiddle won't know about new content in electron-quick-start.

* One possible approach: at runtime when "New Fiddle" is clicked, do a `git clone` (if needed) + `git branch` of electron-quick-start in a scratch dir, then pull content from that directory. We'd probably also want to keep fallback static contents in case we're offline or if GitHub is down. Advantages: futureproof; doesn't need any dependabot upkeep; falls back gracefully to offline. Disadvantage: git needs to be installed?

* Variant of previous approach: instead of `git clone`, download and open a zip from github (e.g. `https://github.com/electron/electron-quick-start/archive/12-x-y.zip`) and unzip it in a cache directory (e.g. `${config_dir}/Electron Fiddle/static/electron-quick-start`). Advantages: same as previous. Disadvantages: ...none that I see? I kind of like this one.

@malept @erickzhao I think I'm going to try out that last approach and see how it works, but am happy to use other ideas e.g. the submodule suggestion if you think it would be better.

**Comment by malept** [comment]
The zip approach seems fine to me as an alternative to an influx of Dependabot PRs. Which I wouldn't mind as much if we could allowlist, for example, the submodule PRs to automerge.

**Pull request closed without merging**
